services:

  sales-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sales-api-mysql:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d